# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\nchatserver\"(\n\x14\x43reateAccountRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"9\n\x15\x43reateAccountResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"$\n\x13ListAccountsRequest\x12\r\n\x05query\x18\x01 \x01(\t\"8\n\x14ListAccountsResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63ounts\x18\x02 \x03(\t\"8\n\x12SendMessageRequest\x12\x11\n\trecipient\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x13SendMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x16\n\x14\x44\x65leteAccountRequest\"\'\n\x15\x44\x65leteAccountResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\" \n\x0cLogInRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"1\n\rLogInResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"\x0f\n\rLogOffRequest\" \n\x0eLogOffResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xe6\x03\n\nChatServer\x12V\n\rCreateAccount\x12 .chatserver.CreateAccountRequest\x1a!.chatserver.CreateAccountResponse\"\x00\x12S\n\x0cListAccounts\x12\x1f.chatserver.ListAccountsRequest\x1a .chatserver.ListAccountsResponse\"\x00\x12P\n\x0bSendMessage\x12\x1e.chatserver.SendMessageRequest\x1a\x1f.chatserver.SendMessageResponse\"\x00\x12V\n\rDeleteAccount\x12 .chatserver.DeleteAccountRequest\x1a!.chatserver.DeleteAccountResponse\"\x00\x12>\n\x05LogIn\x12\x18.chatserver.LogInRequest\x1a\x19.chatserver.LogInResponse\"\x00\x12\x41\n\x06LogOff\x12\x19.chatserver.LogOffRequest\x1a\x1a.chatserver.LogOffResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEACCOUNTREQUEST._serialized_start=28
  _CREATEACCOUNTREQUEST._serialized_end=68
  _CREATEACCOUNTRESPONSE._serialized_start=70
  _CREATEACCOUNTRESPONSE._serialized_end=127
  _LISTACCOUNTSREQUEST._serialized_start=129
  _LISTACCOUNTSREQUEST._serialized_end=165
  _LISTACCOUNTSRESPONSE._serialized_start=167
  _LISTACCOUNTSRESPONSE._serialized_end=223
  _SENDMESSAGEREQUEST._serialized_start=225
  _SENDMESSAGEREQUEST._serialized_end=281
  _SENDMESSAGERESPONSE._serialized_start=283
  _SENDMESSAGERESPONSE._serialized_end=320
  _DELETEACCOUNTREQUEST._serialized_start=322
  _DELETEACCOUNTREQUEST._serialized_end=344
  _DELETEACCOUNTRESPONSE._serialized_start=346
  _DELETEACCOUNTRESPONSE._serialized_end=385
  _LOGINREQUEST._serialized_start=387
  _LOGINREQUEST._serialized_end=419
  _LOGINRESPONSE._serialized_start=421
  _LOGINRESPONSE._serialized_end=470
  _LOGOFFREQUEST._serialized_start=472
  _LOGOFFREQUEST._serialized_end=487
  _LOGOFFRESPONSE._serialized_start=489
  _LOGOFFRESPONSE._serialized_end=521
  _CHATSERVER._serialized_start=524
  _CHATSERVER._serialized_end=1010
# @@protoc_insertion_point(module_scope)
